// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using trelloApi.Context;

namespace trelloApi.Migrations
{
    [DbContext(typeof(YettiContext))]
    partial class YettiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("trelloApi.Domains.Board", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.Property<int?>("UserId");

                    b.HasKey("BoardId");

                    b.HasIndex("UserId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("trelloApi.Domains.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Completed");

                    b.Property<string>("Description");

                    b.Property<bool>("Hide");

                    b.Property<int?>("TableId");

                    b.HasKey("NoteId");

                    b.HasIndex("TableId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("trelloApi.Domains.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BoardId");

                    b.Property<string>("Title");

                    b.HasKey("TableId");

                    b.HasIndex("BoardId");

                    b.ToTable("Table");
                });

            modelBuilder.Entity("trelloApi.Domains.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Avatar");

                    b.Property<string>("Email");

                    b.Property<string>("HashPassword");

                    b.Property<string>("Salt");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("trelloApi.Domains.Board", b =>
                {
                    b.HasOne("trelloApi.Domains.User", "User")
                        .WithMany("Board")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("trelloApi.Domains.Note", b =>
                {
                    b.HasOne("trelloApi.Domains.Table", "Table")
                        .WithMany("Notes")
                        .HasForeignKey("TableId");
                });

            modelBuilder.Entity("trelloApi.Domains.Table", b =>
                {
                    b.HasOne("trelloApi.Domains.Board")
                        .WithMany("Table")
                        .HasForeignKey("BoardId");
                });
#pragma warning restore 612, 618
        }
    }
}
